imported the libraries

In [62]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
%matplotlib inline
from pandas_profiling import ProfileReport
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier

loded the csv dataset 

In [2]:
df = pd.read_csv('winequality-red.csv')
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [3]:
df.shape

(1599, 12)

create x and y by seperating target variable

In [4]:
x = df.drop(columns=['quality'])
y = df['quality']

In [5]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25,random_state=20)

In [6]:
x_train

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
400             6.6             0.735         0.02            7.90      0.122   
35              7.8             0.645         0.00            5.50      0.086   
641             9.5             0.590         0.44            2.30      0.071   
721             8.9             0.480         0.24            2.85      0.094   
1501            7.8             0.820         0.29            4.30      0.083   
...             ...               ...          ...             ...        ...   
924             8.6             0.470         0.27            2.30      0.055   
1247            7.4             0.550         0.19            1.80      0.082   
271            11.5             0.180         0.51            4.00      0.104   
474            10.5             0.280         0.51            1.70      0.080   
1379            7.5             0.570         0.02            2.60      0.077   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
400                  68.0                 124.0  0.99940  3.47       0.53   
35                    5.0                  18.0  0.99860  3.40       0.55   
641                  21.0                  68.0  0.99920  3.46       0.63   
721                  35.0                 106.0  0.99820  3.10       0.53   
1501                 21.0                  64.0  0.99642  3.16       0.53   
...                   ...                   ...      ...   ...        ...   
924                  14.0                  28.0  0.99516  3.18       0.80   
1247                 15.0                  34.0  0.99655  3.49       0.68   
271                   4.0                  23.0  0.99960  3.28       0.97   
474                  10.0                  24.0  0.99820  3.20       0.89   
1379                 11.0                  35.0  0.99557  3.36       0.62   

      alcohol  
400       9.9  
35        9.6  
641       9.5  
721       9.2  
1501      9.4  
...       ...  
924      11.2  
1247     10.5  
271      10.1  
474       9.4  
1379     10.8  

[1199 rows x 11 columns]

In [7]:
x_test

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
1508            7.1              0.27         0.60             2.1      0.074   
718             8.4              0.56         0.04             2.0      0.082   
1370            8.7              0.78         0.51             1.7      0.415   
579            10.6              0.31         0.49             2.2      0.063   
498            10.7              0.35         0.53             2.6      0.070   
...             ...               ...          ...             ...        ...   
1338            6.0              0.50         0.00             1.4      0.057   
860             7.2              0.62         0.06             2.7      0.077   
115             9.4              0.40         0.31             2.2      0.090   
1401            7.9              0.69         0.21             2.1      0.080   
585             7.6              0.51         0.24             2.4      0.091   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
1508                 17.0                  25.0  0.99814  3.38       0.72   
718                  10.0                  22.0  0.99760  3.22       0.44   
1370                 12.0                  66.0  0.99623  3.00       1.17   
579                  18.0                  40.0  0.99760  3.14       0.51   
498                   5.0                  16.0  0.99720  3.15       0.65   
...                   ...                   ...      ...   ...        ...   
1338                 15.0                  26.0  0.99448  3.36       0.45   
860                  15.0                  85.0  0.99746  3.51       0.54   
115                  13.0                  62.0  0.99660  3.07       0.63   
1401                 33.0                 141.0  0.99620  3.25       0.51   
585                   8.0                  38.0  0.99800  3.47       0.66   

      alcohol  
1508     10.6  
718       9.6  
1370      9.2  
579       9.8  
498      11.0  
...       ...  
1338      9.5  
860       9.5  
115      10.5  
1401      9.9  
585       9.6  

[400 rows x 11 columns]

In [8]:
y_train

400     5
35      6
641     5
721     5
1501    5
       ..
924     5
1247    5
271     6
474     6
1379    6
Name: quality, Length: 1199, dtype: int64

In [9]:
y_test

1508    6
718     5
1370    5
579     6
498     8
       ..
1338    5
860     5
115     6
1401    5
585     6
Name: quality, Length: 400, dtype: int64

# Traning model with deafult parameter KNN

In [10]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [11]:
knn.score(x_train,y_train)

0.6513761467889908

In [12]:
knn.score(x_test,y_test)

0.5175

# traning model by modifying parameter of KNN

In [13]:
from sklearn.model_selection import GridSearchCV
param = {
    'n_neighbors':[3, 5,10,15,20,23,25,30,33,35,40],
    'weights':['uniform','distance'],
    'algorithm':['auto', 'ball_tree', 'kd_tree', 'brute'],
    'leaf_size':[10,20,30,40,50,60],
    'p':[1,2],
   
}
grid_param = GridSearchCV(knn, param_grid= param)
grid_param.fit(x_train,y_train)

GridSearchCV(estimator=KNeighborsClassifier(),
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'leaf_size': [10, 20, 30, 40, 50, 60],
                         'n_neighbors': [3, 5, 10, 15, 20, 23, 25, 30, 33, 35,
                                         40],
                         'p': [1, 2], 'weights': ['uniform', 'distance']})

In [14]:
grid_param.best_params_

{'algorithm': 'auto',
 'leaf_size': 10,
 'n_neighbors': 33,
 'p': 1,
 'weights': 'distance'}

In [15]:
knn1 = KNeighborsClassifier(algorithm= 'auto',
 leaf_size= 10,
 n_neighbors= 33,
 p= 1,
 weights= 'distance')

In [16]:
knn1.fit(x_train,y_train)

KNeighborsClassifier(leaf_size=10, n_neighbors=33, p=1, weights='distance')

In [17]:
knn1.score(x_train,y_train)

1.0

In [18]:
knn1.score(x_test,y_test)

0.6225

after parameter tunning we are getting overfitting model, here we can
train model with high range so we can get more generallized model.

# SVM

In [22]:
from sklearn.svm import SVC

In [23]:
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

# traning model with deafult parameter

In [24]:
svc = SVC()
svc.fit(x_train,y_train)

SVC()

In [25]:
svc.score(x_train,y_train)

0.5095913261050876

In [26]:
svc.score(x_test,y_test)

0.5

# traning model with parameter tunning

In [29]:
parameter = {'kernel':['poly','linear','rbf']}
svc_gird = GridSearchCV(svc,param_grid=parameter,cv=10)
svc_gird.fit(x_train,y_train)

C:\Users\Sk\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 8 members, which is less than n_splits=10.
  warnings.warn(("The least populated class in y has only %d"


GridSearchCV(cv=10, estimator=SVC(),
             param_grid={'kernel': ['poly', 'linear', 'rbf']})

In [31]:
svc_gird.best_params_

{'kernel': 'linear'}

Here we have taken kernel = 'linear' from Gridsearchcv

In [32]:
svc_model = SVC(kernel='linear')
svc_model.fit(x_train,y_train)

SVC(kernel='linear')

In [33]:
svc_model.score(x_train,y_train)

0.5829858215179317

In [34]:
svc_model.score(x_test,y_test)

0.5925

Now can get somewhat generalized model, but not best one, we can also
tune other parameters to get more accuracy in train and test dataset.

# SVR

In [35]:
df1 = pd.read_csv('Admission_Prediction.csv')
df1.head()

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR  CGPA  \
0           1      337.0        118.0                4.0  4.5  4.5  9.65   
1           2      324.0        107.0                4.0  4.0  4.5  8.87   
2           3        NaN        104.0                3.0  3.0  3.5  8.00   
3           4      322.0        110.0                3.0  3.5  2.5  8.67   
4           5      314.0        103.0                2.0  2.0  3.0  8.21   

   Research  Chance of Admit  
0         1             0.92  
1         1             0.76  
2         1             0.72  
3         1             0.80  
4         0             0.65

In [49]:
x = df1.drop(['Serial No.','Chance of Admit'], axis=1)
y = df1['Chance of Admit']

In [50]:
x1_train,x1_test,y1_train,y1_test = train_test_split(x,y,test_size=.25,random_state=30)

In [51]:
df1['GRE Score'] = df1['GRE Score'].fillna(df1['GRE Score'].mean())
df1['TOEFL Score'] = df1['TOEFL Score'].fillna(df1['TOEFL Score'].mean())
df1['University Rating'] = df1['University Rating'].fillna(df1['University Rating'].mean())

In [52]:
from sklearn.svm import SVR
svr= SVR()
svr.fit(x1_train,y1_train)

SVR()

In [53]:
svr.score(x1_train,y1_train)

0.6515009756892469

In [54]:
svr.score(x1_test,y1_test)

0.676418968169769

In [56]:
from sklearn.metrics import r2_score
r2_score(y1_test, svr.predict(x1_test))

0.676418968169769

In [58]:
svr.predict(x1_test)

array([0.79216529, 0.57376226, 0.7021406 , 0.64264821, 0.82657694,
       0.75552521, 0.66142074, 0.68903955, 0.73211335, 0.74452152,
       0.82907608, 0.68394455, 0.77134269, 0.88408227, 0.80852922,
       0.82230011, 0.55789278, 0.60363319, 0.75691047, 0.71657385,
       0.70923753, 0.70225874, 0.79032344, 0.80698711, 0.77087568,
       0.57251464, 0.63629504, 0.68020566, 0.62765028, 0.59033685,
       0.67241623, 0.5455408 , 0.78815993, 0.6434272 , 0.66748556,
       0.6643744 , 0.65415218, 0.79513251, 0.55618671, 0.66283329,
       0.5804563 , 0.70785737, 0.68064091, 0.67091028, 0.78310528,
       0.65837308, 0.91108782, 0.63478648, 0.63022818, 0.77714565,
       0.88256401, 0.69662417, 0.793404  , 0.6954175 , 0.6781024 ,
       0.87924114, 0.63971205, 0.54409273, 0.63121137, 0.71460089,
       0.77889168, 0.6902055 , 0.73299792, 0.64376342, 0.71340203,
       0.66952283, 0.66716085, 0.62779689, 0.86083442, 0.68500191,
       0.53350248, 0.86802193, 0.6526466 , 0.54619354, 0.65176

In [60]:
svr.predict([x.iloc[0]])

array([0.88408227])

In [61]:
y1_test[0]

0.92

predicted result is 0.88 and actual result is 0.92 

# Stacking

stacking is the ensable technique along with bagging and boosting

In [64]:
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [65]:
x = df.drop(columns=['quality'])
y = df['quality']

In [68]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.15,random_state=30)

In [69]:
knn = KNeighborsClassifier()
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [70]:
knn.score(x_test,y_test)

0.5083333333333333

In [71]:
svc = SVC()
svc.fit(x_train,y_train)

SVC()

In [72]:
svc.score(x_test,y_test)

0.5125

In [73]:
train, val_train,test,val_test = train_test_split(x,y,test_size=.50,random_state=30)

In [74]:
x_train,x_test,y_train,y_test=train_test_split(train,test,test_size=.30,random_state=30)

In [75]:
prediction_knn = knn.predict(val_train)
prediction_svc = svc.predict(val_train)

In [76]:
prediction_knn

array([7, 5, 6, 5, 5, 5, 5, 5, 6, 5, 6, 5, 6, 6, 7, 6, 5, 6, 5, 5, 5, 6,
       5, 5, 6, 6, 6, 5, 5, 6, 5, 6, 6, 5, 6, 6, 6, 6, 5, 7, 5, 6, 5, 4,
       6, 7, 6, 5, 5, 6, 5, 5, 6, 6, 5, 5, 5, 5, 5, 5, 6, 5, 6, 5, 5, 5,
       5, 6, 5, 4, 5, 5, 5, 5, 6, 6, 7, 5, 5, 6, 6, 7, 6, 5, 5, 5, 5, 6,
       5, 5, 6, 6, 5, 6, 6, 7, 5, 7, 5, 7, 6, 5, 5, 7, 6, 6, 6, 5, 5, 5,
       5, 5, 5, 6, 7, 6, 6, 6, 6, 5, 6, 6, 6, 6, 5, 5, 6, 6, 6, 6, 6, 5,
       5, 5, 7, 5, 5, 5, 6, 7, 7, 5, 5, 5, 6, 5, 5, 5, 5, 7, 5, 5, 5, 6,
       5, 7, 6, 7, 7, 5, 5, 6, 6, 5, 6, 5, 5, 6, 7, 6, 6, 6, 5, 6, 5, 5,
       5, 5, 6, 6, 5, 6, 6, 5, 5, 6, 5, 7, 6, 6, 5, 5, 6, 5, 7, 5, 6, 5,
       5, 6, 6, 6, 6, 5, 5, 6, 7, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 6, 7, 5,
       6, 6, 5, 6, 6, 5, 6, 5, 6, 5, 6, 6, 5, 6, 6, 5, 5, 6, 5, 6, 5, 6,
       5, 6, 5, 6, 6, 5, 6, 6, 5, 6, 5, 6, 5, 5, 5, 5, 5, 6, 5, 5, 6, 6,
       4, 5, 6, 6, 6, 6, 5, 5, 6, 6, 5, 6, 4, 6, 5, 6, 5, 5, 5, 6, 5, 6,
       7, 6, 5, 7, 5, 5, 6, 7, 5, 6, 5, 6, 5, 6, 5,

In [77]:
prediction_svc

array([6, 6, 6, 5, 6, 5, 6, 5, 5, 5, 6, 5, 6, 6, 5, 6, 6, 5, 6, 5, 6, 6,
       6, 5, 6, 6, 6, 6, 5, 6, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 6, 5, 5, 5, 5, 5, 6, 5, 6, 6, 5, 5,
       5, 6, 5, 6, 5, 5, 6, 6, 6, 6, 6, 5, 6, 6, 6, 6, 6, 6, 5, 6, 5, 6,
       5, 6, 5, 6, 5, 6, 6, 6, 5, 6, 5, 6, 5, 6, 6, 6, 6, 6, 6, 5, 6, 5,
       5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 6, 6, 6, 5, 5, 5,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 6, 5, 6, 6, 6, 6, 5, 5, 6, 6,
       6, 6, 6, 6, 6, 6, 5, 6, 5, 5, 6, 5, 6, 6, 6, 6, 6, 5, 6, 6, 6, 6,
       5, 5, 6, 6, 5, 6, 6, 5, 5, 6, 6, 6, 5, 6, 5, 6, 6, 5, 6, 6, 6, 5,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 6, 6, 5,
       6, 6, 5, 6, 6, 6, 6, 5, 6, 6, 6, 6, 6, 6, 6, 6, 5, 6, 6, 6, 5, 6,
       6, 6, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 6, 6, 5, 6, 6,
       6, 5, 6, 5, 6, 6, 5, 6, 6, 6, 5, 6, 6, 6, 6, 6, 6, 5, 6, 6, 6, 5,
       6, 6, 5, 6, 5, 6, 6, 6, 6, 6, 5, 5, 5, 6, 5,

In [80]:
input3 = np.column_stack((prediction_knn,prediction_svc))

In [83]:
output = val_test
output

1147    7
659     4
871     5
1333    5
1411    6
       ..
1073    6
200     7
942     7
1106    6
1329    6
Name: quality, Length: 800, dtype: int64

In [85]:
pd.DataFrame(input3)

0  1
0    7  6
1    5  6
2    6  6
3    5  5
4    5  6
..  .. ..
795  5  6
796  5  6
797  6  5
798  6  6
799  6  5

[800 rows x 2 columns]

In [87]:
rf =RandomForestClassifier()
rf.fit(input3,output)

RandomForestClassifier()

In [90]:
knn_prediction_output=knn.predict(x_test)
svc_prediction_output=svc.predict(x_test)

In [91]:
output_stack = np.column_stack((knn_prediction_output,svc_prediction_output))
rf.predict(output_stack)

array([5, 6, 6, 5, 6, 6, 6, 6, 6, 5, 6, 6, 5, 5, 6, 6, 6, 6, 5, 6, 5, 7,
       5, 5, 5, 5, 5, 6, 5, 5, 6, 5, 6, 5, 5, 6, 6, 6, 6, 5, 6, 6, 5, 6,
       6, 7, 5, 5, 5, 5, 6, 5, 6, 5, 5, 6, 6, 6, 6, 5, 5, 6, 5, 6, 7, 5,
       5, 5, 6, 6, 6, 6, 5, 5, 6, 6, 7, 5, 5, 5, 6, 7, 5, 5, 5, 6, 5, 6,
       6, 6, 6, 5, 6, 5, 5, 6, 7, 5, 5, 5, 5, 6, 6, 5, 5, 6, 6, 7, 6, 6,
       5, 6, 6, 5, 6, 5, 7, 7, 5, 5, 7, 6, 6, 6, 6, 6, 5, 5, 5, 5, 7, 7,
       6, 6, 6, 6, 6, 5, 5, 6, 5, 5, 6, 5, 6, 5, 5, 6, 5, 6, 6, 5, 6, 7,
       5, 5, 5, 5, 6, 5, 5, 5, 6, 5, 5, 6, 5, 5, 5, 5, 7, 6, 6, 6, 5, 6,
       5, 6, 5, 7, 5, 5, 7, 5, 6, 6, 6, 6, 5, 5, 5, 6, 5, 5, 6, 7, 5, 5,
       5, 5, 6, 5, 6, 6, 6, 7, 5, 6, 6, 6, 6, 5, 6, 5, 5, 6, 6, 5, 5, 5,
       6, 6, 6, 7, 5, 5, 5, 6, 5, 6, 5, 5, 6, 6, 6, 5, 6, 6, 5, 5],
      dtype=int64)

In [92]:
rf.score(output_stack,y_test)

0.65